<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventPlanner.Data\Aladin.Data.csproj" />
    <ProjectReference Include="..\EventPlanner.Domain\Aladin.Domain.csproj" />
    <ProjectReference Include="..\Service.Pattern\Service.Pattern.csproj" />
  </ItemGroup>

</Project>
